---
- hosts: web
  tasks:
    - name: Create devops user
      user:
        name: devops
        state: present
    - name: Install apache2
      package:
        name: apache2
        state: present
    - name: Check if apache is started
      service:
        name: apache2
        state: started
    - name: Create directory in apache
      file:
        name: /var/www/html/webapp
        mode: 0777
        state: directory
    - name: Create file inside webapp directory
      file: 
        name: /var/www/html/webapp/index.html
        state: touch
