---
- hosts: web
  tasks:
    - name: Copy file
      copy:
        src: copy.html
        dest: /tmp/
      notify:
        - restart_apache
    - name: Create directory
      file:
        name: /tmp/test
        state: directory
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
