---
- hosts: web
  tasks:
    - name: install apache
      apt: 
        name: apache2
        state: present
    - name: Check service
      service:
        name: apache2
        state: started
    - name: Copy html file
      copy:
        src: copy.html
        dest: /var/www/html/
    - name: Template of copy file
      template:
        src: copy.html.j2
        dest: /var/www/html/template.html
